spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_social_network
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver  # Corrected driver class name for MySQL

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Specify MySQL dialect

  mail:
    host: localhost
    port: 1025
    username: ali
    password: ali
    properties:
      mail:
        smtp:
          trust: "*"   # Adjusted formatting

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    uploads:
      photos-output-path: ./uploads

server:
  port: 8088
